In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot

# ***DATA PREPROCESSING***

In [2]:
df = pd.read_csv("Anemia.csv")
df

Number Sex  %Red Pixel  %Green pixel  %Blue pixel    Hb Anaemic
0         1   M     43.2555       30.8421      25.9025   6.3     Yes
1         2   F     45.6033       28.1900      26.2067  13.5      No
2         3  F      45.0107       28.9677      26.0215  11.7      No
3         4   F     44.5398       28.9899      26.4703  13.5      No
4         5  M      43.2870       30.6972      26.0158  12.4      No
..      ...  ..         ...           ...          ...   ...     ...
99      100  F      49.9999       29.2860      20.7141  14.5     Yes
100     101  M      42.2324       30.6757      27.0919   6.3     Yes
101     102   F     45.6064       31.9084      22.4852  12.7      No
102     103  M      45.2095       29.2769      25.5136  13.4      No
103     104   F     43.5706       29.8094      26.6199  12.2      No

[104 rows x 7 columns]

In [3]:
X = np.array(df.iloc[:, 1:-1].values)
y = np.array(df.iloc[:, -1].values)
print(X)
print(y)

[['M' 43.2555 30.8421 25.9025 6.3]
 ['F' 45.6033 28.19 26.2067 13.5]
 ['F ' 45.0107 28.9677 26.0215 11.7]
 ['F' 44.5398 28.9899 26.4703 13.5]
 ['M ' 43.287 30.6972 26.0158 12.4]
 ['M' 45.0994 27.9645 26.9361 16.2]
 ['F' 43.1457 30.1628 26.6915 8.6]
 ['F ' 43.6103 29.1099 27.2798 10.3]
 ['F' 45.0423 29.166 25.7918 13.0]
 ['F' 46.5143 27.4282 26.0575 9.7]
 ['F' 45.3506 29.1248 25.5246 12.6]
 ['F' 44.4062 28.9298 26.664 15.4]
 ['F' 44.9642 30.5279 24.5079 4.8]
 ['M ' 45.0484 31.1049 23.8467 9.0]
 ['M ' 46.9942 26.0496 26.9562 14.6]
 ['M' 45.5842 28.7311 25.6848 14.0]
 ['F' 42.5358 30.1604 27.3039 10.0]
 ['F' 44.0957 29.9973 25.907 8.3]
 ['F' 45.7104 27.5693 26.7204 13.6]
 ['F ' 40.9365 31.9687 27.0948 9.9]
 ['F' 44.9116 30.3761 24.7123 11.6]
 ['F ' 43.4225 29.7889 26.7886 12.4]
 ['F' 43.3019 29.8285 26.8697 12.1]
 ['F ' 47.6372 26.7953 25.5675 15.1]
 ['M' 45.6906 30.0735 24.2359 9.1]
 ['M ' 43.4098 31.2315 25.3586 12.9]
 ['F' 44.4252 28.7436 26.8312 14.7]
 ['M' 44.3297 28.7617 26.9086 14.

In [4]:
x_gender = []
for i in X[:, 0]:
  x_gender.append(i.rstrip())
X[:, 0] = x_gender

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 43.2555 30.8421 25.9025 6.3]
 [1.0 0.0 45.6033 28.19 26.2067 13.5]
 [1.0 0.0 45.0107 28.9677 26.0215 11.7]
 [1.0 0.0 44.5398 28.9899 26.4703 13.5]
 [0.0 1.0 43.287 30.6972 26.0158 12.4]
 [0.0 1.0 45.0994 27.9645 26.9361 16.2]
 [1.0 0.0 43.1457 30.1628 26.6915 8.6]
 [1.0 0.0 43.6103 29.1099 27.2798 10.3]
 [1.0 0.0 45.0423 29.166 25.7918 13.0]
 [1.0 0.0 46.5143 27.4282 26.0575 9.7]
 [1.0 0.0 45.3506 29.1248 25.5246 12.6]
 [1.0 0.0 44.4062 28.9298 26.664 15.4]
 [1.0 0.0 44.9642 30.5279 24.5079 4.8]
 [0.0 1.0 45.0484 31.1049 23.8467 9.0]
 [0.0 1.0 46.9942 26.0496 26.9562 14.6]
 [0.0 1.0 45.5842 28.7311 25.6848 14.0]
 [1.0 0.0 42.5358 30.1604 27.3039 10.0]
 [1.0 0.0 44.0957 29.9973 25.907 8.3]
 [1.0 0.0 45.7104 27.5693 26.7204 13.6]
 [1.0 0.0 40.9365 31.9687 27.0948 9.9]
 [1.0 0.0 44.9116 30.3761 24.7123 11.6]
 [1.0 0.0 43.4225 29.7889 26.7886 12.4]
 [1.0 0.0 43.3019 29.8285 26.8697 12.1]
 [1.0 0.0 47.6372 26.7953 25.5675 15.1]
 [0.0 1.0 45.6906 30.0735 24.2359 9.1]
 [0.0 1.0 43.4

In [6]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
y = le.fit_transform(y)
print(y)

[1 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 0 1 1 0 1 0 0
 0 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0]


### ***SPLITTING***

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.225, random_state = 1)
print(X_train)

[[0.0 1.0 46.7628 28.018 25.2192 15.2]
 [0.0 1.0 41.7122 30.1452 28.1426 10.9]
 [0.0 1.0 45.4735 27.9181 26.6084 16.0]
 [0.0 1.0 46.7979 28.1768 25.0253 14.0]
 [0.0 1.0 48.5356 26.4917 24.9727 15.6]
 [1.0 0.0 46.4081 28.1641 25.4278 13.5]
 [1.0 0.0 45.3506 29.1248 25.5246 12.6]
 [1.0 0.0 45.0107 28.9677 26.0215 11.7]
 [0.0 1.0 42.1652 29.3907 28.4441 13.4]
 [1.0 0.0 46.9597 28.4993 24.541 8.4]
 [1.0 0.0 40.9365 31.9687 27.0948 9.9]
 [0.0 1.0 44.3297 28.7617 26.9086 14.1]
 [1.0 0.0 45.8483 27.2043 26.9474 15.5]
 [1.0 0.0 49.9999 29.286 20.7141 14.5]
 [1.0 0.0 42.4532 30.9448 26.602 9.2]
 [0.0 1.0 44.72 28.0357 27.2443 14.0]
 [0.0 1.0 46.0477 28.6476 25.3047 14.4]
 [0.0 1.0 46.2133 28.3358 25.4509 13.0]
 [1.0 0.0 45.9707 30.9397 23.0896 8.7]
 [1.0 0.0 47.6372 26.7953 25.5675 15.1]
 [1.0 0.0 42.1528 30.432 27.4152 13.7]
 [1.0 0.0 46.3745 28.882 24.7435 10.7]
 [1.0 0.0 44.1995 29.486 26.3145 11.2]
 [0.0 1.0 49.5037 26.7716 23.7246 14.5]
 [0.0 1.0 45.5842 28.7311 25.6848 14.0]
 [0.0 1.0 46.

In [8]:
print(X_test)

[[1.0 0.0 51.5802 28.2678 20.152 13.2]
 [0.0 1.0 45.2588 28.0079 26.7333 12.6]
 [1.0 0.0 42.8269 29.0594 28.1137 12.7]
 [1.0 0.0 50.3562 29.2206 20.4232 11.9]
 [1.0 0.0 47.3642 27.473 25.1628 11.8]
 [0.0 1.0 46.1449 27.7085 26.1466 14.1]
 [1.0 0.0 47.1003 28.3195 24.5801 12.4]
 [1.0 0.0 46.255 27.2758 26.4692 11.0]
 [0.0 1.0 48.6358 26.6982 24.666 15.0]
 [0.0 1.0 49.1475 28.2711 22.5813 12.6]
 [0.0 1.0 47.326 27.278 25.396 13.0]
 [0.0 1.0 48.8523 26.2003 24.9474 14.1]
 [0.0 1.0 43.1425 30.289 26.5686 9.5]
 [0.0 1.0 40.6395 32.1891 27.1714 2.8]
 [0.0 1.0 45.4434 28.3301 26.2265 14.5]
 [0.0 1.0 54.6478 25.8109 19.5413 15.2]
 [1.0 0.0 43.5706 29.8094 26.6199 12.2]
 [1.0 0.0 43.8783 29.4752 26.6465 14.1]
 [1.0 0.0 44.0957 29.9973 25.907 8.3]
 [1.0 0.0 45.6064 31.9084 22.4852 12.7]
 [1.0 0.0 44.1609 29.5993 26.2399 12.5]
 [1.0 0.0 43.1335 29.3459 27.5206 10.4]
 [0.0 1.0 44.1609 29.5993 26.2399 9.5]
 [0.0 1.0 44.1868 28.9764 26.8368 14.1]]


### ***FEATURE SCALING***

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,2:] = sc.fit_transform(X_train[:,2:])
X_test[:,2:] = sc.transform(X_test[:,2:])

In [10]:
print(X_train)

[[0.0 1.0 0.46867962148347736 -0.5869720532267334 -0.1898024153111469
  1.22684988575816]
 [0.0 1.0 -1.4155109267837125 0.7907574274919627 1.3953886195802319
  -0.5135062408431057]
 [0.0 1.0 -0.012310136937479533 -0.6516745612766582 0.5634805379867599
  1.550637072102582]
 [0.0 1.0 0.4817741227792003 -0.4841216200102384 -0.2949431903215584
  0.7411691062415279]
 [0.0 1.0 1.130045202596233 -1.5755149765160086 -0.3234651334136051
  1.388743478930371]
 [1.0 0.0 0.33635427648082916 -0.49234706397654426 -0.07669067901835684
  0.5388021147762644]
 [1.0 0.0 -0.05815954460825931 0.12987215007312256 -0.024201627852767946
  0.17454153013878992]
 [1.0 0.0 -0.18496356142923476 0.028122760537156472 0.24523855318216603
  -0.18971905449868454]
 [0.0 1.0 -1.2465135168987425 0.3020883351629587 1.5588746622085914
  0.4983287164832118]
 [1.0 0.0 0.5421356700626182 -0.2752471570863093 -0.5575511188287405
  -1.5253411981694232]
 [1.0 0.0 -1.7048956747920405 1.971788693047878 0.8272271752485667
  -0.9182402

In [11]:
print(X_test)

[[1.0 0.0 2.265871944617831 -0.4251833994642611 -2.937452415995826
  0.417381919897106]
 [0.0 1.0 -0.09240670184322679 -0.5935135480345844 0.631206596773766
  0.17454153013878992]
 [1.0 0.0 -0.9996579183978898 0.08751435201040947 1.3797178181475298
  0.21501492843184247]
 [1.0 0.0 1.8092431814849288 0.19191919983471145 -2.790396313969917
  -0.1087722579125787]
 [1.0 0.0 0.693039538271163 -0.9399537037493417 -0.22038487900680048
  -0.14924565620563127]
 [0.0 1.0 0.23816416989865666 -0.787426770358379 0.3130730604219933
  0.7816425045345804]
 [1.0 0.0 0.5945882877885054 -0.3916987181211072 -0.5363494463021431
  0.0935947335526848]
 [1.0 0.0 0.27923837481772035 -1.067674770690732 0.48800041482301976
  -0.4730328425500532]
 [0.0 1.0 1.1674260866370152 -1.4417705529693705 -0.4897708358153239
  1.145903089172055]
 [0.0 1.0 1.3583222778911865 -0.4230460793785283 -1.6201832837998824
  0.17454153013878992]
 [0.0 1.0 0.6787885425590101 -1.0662498906335776 -0.09393398301697031
  0.336435123311000

# ***CLASSIFICATION MODELS***

### ***LOGISTIC REGRRESSION***


In [12]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [13]:
#print(lr.predict(sc.transform([])))

In [14]:
y_pred_lr = lr.predict(X_test)
print(np.concatenate((y_pred_lr.reshape(len(y_pred_lr), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]]


In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_lr)
print(cm)
accuracy_score(y_test, y_pred_lr)

[[17  2]
 [ 2  3]]


0.8333333333333334

### ***KNN***

In [16]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
kn.fit(X_train,y_train)

KNeighborsClassifier()

In [17]:
y_pred_kn = kn.predict(X_test)
print(np.concatenate((y_pred_kn.reshape(len(y_pred_kn), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]]


In [18]:
cm2 = confusion_matrix(y_test, y_pred_kn)
print(cm2)
accuracy_score(y_test, y_pred_kn)

[[19  0]
 [ 2  3]]


0.9166666666666666

### ***SVM***

In [19]:
from sklearn.svm import SVC
svc = SVC(kernel = 'linear', random_state = 0)
svc.fit(X_train,y_train)

SVC(kernel='linear', random_state=0)

In [20]:
y_pred_svc = svc.predict(X_test)
print(np.concatenate((y_pred_svc.reshape(len(y_pred_svc), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]]


In [21]:
cm3 = confusion_matrix(y_test, y_pred_svc)
print(cm3)
accuracy_score(y_test, y_pred_svc)

[[18  1]
 [ 1  4]]


0.9166666666666666

### ***Naive Bayes***

In [22]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train, y_train)

GaussianNB()

In [23]:
y_pred_nb = nb.predict(X_test)
print(np.concatenate((y_pred_nb.reshape(len(y_pred_nb), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]]


In [24]:
cm4 = confusion_matrix(y_test, y_pred_nb)
print(cm4)
accuracy_score(y_test, y_pred_nb)

[[18  1]
 [ 0  5]]


0.9583333333333334

### ***DECISION TREE***

In [25]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [26]:
y_pred_dt = dt.predict(X_test)
print(np.concatenate((y_pred_dt.reshape(len(y_pred_dt), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]]


In [27]:
cm5 = confusion_matrix(y_test, y_pred_dt)
print(cm5)
accuracy_score(y_test, y_pred_dt)

[[19  0]
 [ 0  5]]


1.0

### ***RANDOM FOREST***

In [28]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rf.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [29]:
y_pred_rf = rf.predict(X_test)
print(np.concatenate((y_pred_nb.reshape(len(y_pred_nb), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]]


In [30]:
cm6 = confusion_matrix(y_test, y_pred_rf)
print(cm6)
accuracy_score(y_test, y_pred_rf)

[[19  0]
 [ 1  4]]


0.9583333333333334

In [31]:
import pickle
with open('anemia_pred.pkl', 'wb') as f:
    pickle.dump(nb, f)
with open('scaler.pkl', 'wb') as f:
    pickle.dump(sc, f)